import sys

import pandas as pd
import matplotlib

matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib import rcParams


# This script plots the study population against multiple 1000 genome project
# populations on the first two population axes.
#
# It used to read a PLINK 1.9 --mds-plot file (FID IID SOL C1 C2). PLINK 2 has
# no MDS support, so data_checkpopulation.sh now produces principal components
# instead and this script reads a PLINK 2 .eigenvec table (#FID IID PC1 PC2).
#
# INPUTS:
#   eigenvec_file: population coordinates written by data_checkpopulation.sh,
#       "#FID IID PC1 PC2". A legacy PLINK 1.9 .mds file (FID IID SOL C1 C2) is
#       also accepted, in which case C1/C2 are plotted.
#   pop_id_file: population data (FID, IID) combined with one-hot encoded
#       sub-population membership. This is generated by data_checkpopulation.sh.
#   legend_pos: legend position, one of southeast, southwest, northeast,
#       northwest, best.
#   outfile: output file name. pdf extension will be added.
#
# OUTPUTS:
#   A outfile.pdf file showing the scatter plot on the top two population axes.
#   Different populations are colored differently.

# Example inputs
# eigenvec_file = 'gwas_subset_prj1000.eigenvec'
# pop_id_file = 'allpopid.txt'
# legend_pos = 'southeast'
# outfile = 'PCA_gwas_subset'

LEGEND_LOC = {
    'southeast': 'lower right',
    'southwest': 'lower left',
    'northeast': 'upper right',
    'northwest': 'upper left',
    'best': 'best',
}


def read_coordinates(path):
    """Read a plink2 .eigenvec, or a legacy plink 1.9 .mds file."""
    data = pd.read_csv(path, index_col=False, sep=r'\s+')
    data.columns = [str(c).lstrip('#') for c in data.columns]

    if 'PC1' in data.columns and 'PC2' in data.columns:
        xcol, ycol = 'PC1', 'PC2'
    elif 'C1' in data.columns and 'C2' in data.columns:
        xcol, ycol = 'C1', 'C2'
    else:
        raise SystemExit(
            'Cannot find PC1/PC2 (or C1/C2) columns in %s, found: %s'
            % (path, ', '.join(map(str, data.columns)))
        )

    if 'FID' not in data.columns or 'IID' not in data.columns:
        raise SystemExit('Cannot find FID/IID columns in %s' % path)

    return data[['FID', 'IID', xcol, ycol]], xcol, ycol


def read_populations(path):
    """Read the one-hot population membership file.

    Line 1 holds the population names, one per one-hot column; the remaining
    lines are FID IID followed by the one-hot values.
    """
    with open(path) as handle:
        pop_names = handle.readline().split()

    data = pd.read_csv(path, header=None, skiprows=1, sep=r'\s+')
    expected = len(pop_names) + 2
    if data.shape[1] != expected:
        raise SystemExit(
            '%s has %d columns, expected %d (FID, IID and %d populations)'
            % (path, data.shape[1], expected, len(pop_names))
        )
    data.columns = ['FID', 'IID'] + pop_names
    return data, pop_names


if __name__ == '__main__':
    rcParams['font.family'] = 'sans-serif'
    eigenvec_file = sys.argv[1]
    pop_id_file = sys.argv[2]
    legend_pos = sys.argv[3] if len(sys.argv) > 3 else 'southeast'
    outfile = sys.argv[4]

    coords, xcol, ycol = read_coordinates(eigenvec_file)
    pop_id_data, pop_names = read_populations(pop_id_file)

    # FID/IID come from the same plink run on both sides, but read_csv can still
    # infer different dtypes (e.g. all-numeric IDs in one file), so align them
    for col in ('FID', 'IID'):
        coords[col] = coords[col].astype(str)
        pop_id_data[col] = pop_id_data[col].astype(str)

    data = coords.merge(pop_id_data, how='inner', on=['FID', 'IID'])
    if data.empty:
        raise SystemExit(
            'No samples in common between %s and %s' % (eigenvec_file, pop_id_file)
        )

    data['population'] = (data[pop_names] == 1).idxmax(axis=1)

    # draw the study samples last so they sit on top of the reference clouds,
    # but list them first in the legend
    study_points = data[data['population'] == 'StudyPop']
    other_points = data[data['population'] != 'StudyPop']
    plot_order = ['StudyPop'] + [p for p in sorted(pop_names) if p != 'StudyPop']

    # Plot with matplotlib rather than seaborn.scatterplot: with an unfilled
    # marker such as '+', seaborn 0.13 leaves the edge color of a subset of the
    # points at the default, and since '+' is drawn entirely by its edge those
    # points come out black instead of their population color.
    fig, ax = plt.subplots()
    colors = plt.get_cmap('tab10').colors
    for i, pop in enumerate(plot_order):
        subset = data[data['population'] == pop]
        if subset.empty:
            continue
        ax.scatter(subset[xcol], subset[ycol], marker='+', s=40,
                   linewidths=0.9, color=colors[i % len(colors)], label=pop,
                   zorder=2 if pop == 'StudyPop' else 3)

    ax.set_title('Population plot colored by population')
    ax.set_xlabel(xcol)
    ax.set_ylabel(ycol)
    ax.grid(zorder=0)
    ax.legend(loc=LEGEND_LOC.get(legend_pos, 'best'), fontsize='small')
    fig.savefig(outfile + '.pdf', bbox_inches='tight')
    plt.close(fig)

    print('%s samples plotted (%s study, %s reference)'
          % (len(data), len(study_points), len(other_points)))
